jobs:
  include:
    - stage: test
      language: node_js
      node_js:
        - "12"
      dist: trusty
      env:
        - NODE_ENV=ci
      cache:
        directories:
        - node_modules
      script:
        - npm run lint
        - npm run build
        - npm run test
