jobs:
  include:
    - stage: test
      language: node_js
      node_js:
        - "8"
      dist: trusty
      env:
        - NODE_ENV=ci
      cache:
        directories:
        - node_modules
      script:
        - npm run lint:fix
        - npm run build
        - npm run test
    - stage: deploy
      if: (NOT type IN (pull_request)) AND (branch = master)
      script:
        - openssl aes-256-cbc -K $encrypted_fc1c34415af5_key -iv $encrypted_fc1c34415af5_iv
          -in deploy_key.enc -out ./deploy_key -d
        - eval "$(ssh-agent -s)"
        - chmod 600 ./deploy_key
        - echo -e "Host $gcpip\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
        - ssh-add ./deploy_key
        - ./deploy-documentation.sh $gcpip

